<?php
/**
 * SignatureFrameSettings
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BoldSign
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BoldSign\Model;

use \ArrayAccess;
use \BoldSign\ObjectSerializer;

/**
 * SignatureFrameSettings Class Doc Comment
 *
 * @category Class
 * @package  BoldSign
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SignatureFrameSettings implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SignatureFrameSettings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'enable_signature_frame' => 'bool',
        'show_recipient_name' => 'bool',
        'show_recipient_email' => 'bool',
        'show_time_stamp' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'enable_signature_frame' => null,
        'show_recipient_name' => null,
        'show_recipient_email' => null,
        'show_time_stamp' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'enable_signature_frame' => false,
        'show_recipient_name' => false,
        'show_recipient_email' => false,
        'show_time_stamp' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'enable_signature_frame' => 'enableSignatureFrame',
        'show_recipient_name' => 'showRecipientName',
        'show_recipient_email' => 'showRecipientEmail',
        'show_time_stamp' => 'showTimeStamp'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'enable_signature_frame' => 'setEnableSignatureFrame',
        'show_recipient_name' => 'setShowRecipientName',
        'show_recipient_email' => 'setShowRecipientEmail',
        'show_time_stamp' => 'setShowTimeStamp'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'enable_signature_frame' => 'getEnableSignatureFrame',
        'show_recipient_name' => 'getShowRecipientName',
        'show_recipient_email' => 'getShowRecipientEmail',
        'show_time_stamp' => 'getShowTimeStamp'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('enable_signature_frame', $data ?? [], false);
        $this->setIfExists('show_recipient_name', $data ?? [], false);
        $this->setIfExists('show_recipient_email', $data ?? [], false);
        $this->setIfExists('show_time_stamp', $data ?? [], false);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets enable_signature_frame
     *
     * @return bool|null
     */
    public function getEnableSignatureFrame()
    {
        return $this->container['enable_signature_frame'];
    }

    /**
     * Sets enable_signature_frame
     *
     * @param bool|null $enable_signature_frame enable_signature_frame
     *
     * @return self
     */
    public function setEnableSignatureFrame($enable_signature_frame)
    {
        if (is_null($enable_signature_frame)) {
            throw new \InvalidArgumentException('non-nullable enable_signature_frame cannot be null');
        }
        $this->container['enable_signature_frame'] = $enable_signature_frame;

        return $this;
    }

    /**
     * Gets show_recipient_name
     *
     * @return bool|null
     */
    public function getShowRecipientName()
    {
        return $this->container['show_recipient_name'];
    }

    /**
     * Sets show_recipient_name
     *
     * @param bool|null $show_recipient_name show_recipient_name
     *
     * @return self
     */
    public function setShowRecipientName($show_recipient_name)
    {
        if (is_null($show_recipient_name)) {
            throw new \InvalidArgumentException('non-nullable show_recipient_name cannot be null');
        }
        $this->container['show_recipient_name'] = $show_recipient_name;

        return $this;
    }

    /**
     * Gets show_recipient_email
     *
     * @return bool|null
     */
    public function getShowRecipientEmail()
    {
        return $this->container['show_recipient_email'];
    }

    /**
     * Sets show_recipient_email
     *
     * @param bool|null $show_recipient_email show_recipient_email
     *
     * @return self
     */
    public function setShowRecipientEmail($show_recipient_email)
    {
        if (is_null($show_recipient_email)) {
            throw new \InvalidArgumentException('non-nullable show_recipient_email cannot be null');
        }
        $this->container['show_recipient_email'] = $show_recipient_email;

        return $this;
    }

    /**
     * Gets show_time_stamp
     *
     * @return bool|null
     */
    public function getShowTimeStamp()
    {
        return $this->container['show_time_stamp'];
    }

    /**
     * Sets show_time_stamp
     *
     * @param bool|null $show_time_stamp show_time_stamp
     *
     * @return self
     */
    public function setShowTimeStamp($show_time_stamp)
    {
        if (is_null($show_time_stamp)) {
            throw new \InvalidArgumentException('non-nullable show_time_stamp cannot be null');
        }
        $this->container['show_time_stamp'] = $show_time_stamp;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


